name: Digger IaC

on:
  pull_request:
    branches: [main]
  issue_comment:
    types: [created]

permissions:
  contents: read
  id-token: write
  pull-requests: write
  issues: write
  statuses: write

jobs:
  digger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Run Digger
        uses: diggerhq/digger@v0.6.0
        with:
          setup-terraform: true
          terraform-version: "1.7.0"
          no-backend: "true"
          configure-checkout: false
          disable-locking: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
